export const surpriseMePrompts = [
  "A futuristic cityscape with flying cars",
  "A magical forest with a waterfall and fairies",
  "A dragon flying over a castle",
  "A unicorn in a field of flowers",
  "A beach with palm trees and crystal-clear water",
  "A robot walking through a city street",
  "A fantasy creature battling a dragon",
  "A space station orbiting a distant planet",
  "A mermaid swimming in the ocean",
  "A steampunk airship flying through the clouds",
  "A haunted forest with ghosts and ghouls",
  "A futuristic spacecraft exploring the universe",
  "A snowy mountain with a cabin in the distance",
  "A post-apocalyptic wasteland with a survivor",
  "A giant robot fighting a giant monster",
  "A futuristic city with a monorail",
  "A pirate ship on the high seas",
  "A cyberpunk city with neon lights",
  "A mythical creature such as a phoenix or a griffin",
  "A train traveling through a canyon",
  "A futuristic sports stadium with holographic displays",
  "A steampunk robot",
  "A city with flying cars and towering skyscrapers",
  "A fairy tale castle with a moat",
  "A fantasy landscape with floating islands",
  "An underwater city with mermaids and sea monsters",
  "A giant tree with a treehouse in its branches",
  "A spacecraft landing on an alien planet",
  "A superhero battling a villain",
  "A mecha robot fighting an alien invasion",
  "A post-apocalyptic city with mutants and scavengers",
  "A city with a massive robot defending it from attack",
  "A mythical creature such as a centaur or a minotaur",
  "A futuristic military base on a distant planet",
  "A magical castle in the clouds",
  "A robotic animal in a natural setting",
  "A city with a massive dome protecting it from the elements",
  "A fantasy battle with wizards and dragons",
  "A city with a massive wall protecting it from attack",
  "A futuristic city with advanced technology",
  "A spaceship battling an asteroid field",
  "A city with a massive statue of a hero or deity",
  "A futuristic hovercraft on a mission",
  "A city with a massive fountain in the center",
  "A fantasy landscape with giant mushrooms and magical plants",
  "A futuristic laboratory with high-tech equipment",
  "A city with a massive arena for sporting events",
  "A steampunk submarine exploring the ocean depths",
  "A city with a massive library containing all knowledge",
  "A futuristic battleship on the open sea",
  "A city with a massive clock tower",
  "A futuristic cityscape with hoverbikes and holographic billboards",
  "An enchanted forest with a unicorn and a hidden pond",
  "A medieval castle with a dragon guarding the entrance",
  "A mystical meadow with a herd of unicorns grazing",
  "A tropical beach with a hammock and a tiki bar",
  "A cybernetic android exploring a bustling city street",
  "A steampunk dirigible hovering above a crowded city street",
  "A haunted mansion with a ghostly apparition in the window",
  "An underwater cavern with a glowing sea creature",
  "A snowy mountain peak with a lone skier making their way down",
  "A futuristic sports arena with high-speed hovercar races",
  "A cosmic battle between spaceships and a massive alien mothership",
  "A city with towering skyscrapers and an elevated monorail system",
  "A rainforest with a hidden waterfall and exotic wildlife",
  "A fantasy village with hobbit holes and a dragon flying overhead",
  "A mystical garden with a fairy queen and her court",
  "A futuristic laboratory with advanced robotic assistants",
  "An abandoned factory with robotic drones patrolling the perimeter",
  "A medieval battlefield with knights jousting on horseback",
  "A futuristic city with a massive energy shield protecting it from an impending invasion",
  "A post-apocalyptic wasteland with a lone survivor navigating the ruins",
  "A jungle with an ancient temple hidden deep within",
  "A city with massive underground tunnels and secret passages",
  "A lunar colony with a bustling population and advanced technology",
  "A city with a towering spire and a hidden laboratory at the top",
  "A futuristic car showroom with sleek, high-tech vehicles on display",
  "A giant futuristic robot fighting off an army of enemy robots",
  "A seaside resort with palm trees, crystal-clear water, and luxury yachts",
  "A massive spaceship docked at a space station with robots loading cargo",
  "A medieval castle with a moat and a drawbridge guarding the entrance",
  "A fantasy landscape with a unicorn herd and a fairy tale cottage in the distance",
  "A futuristic city with flying cars and neon skyscrapers",
  "A mythical creature such as a kraken or a chimera wreaking havoc in a city",
  "A massive colosseum with gladiators battling fierce beasts",
  "A post-apocalyptic city with survivors scavenging for resources",
  "A medieval village with thatched roof cottages and a bustling market",
  "A futuristic army base with high-tech weaponry and soldiers in powered armor",
  "A dystopian city with towering walls and heavy security",
  "A fantasy landscape with a dragon flying over a castle",
  "A futuristic city with massive floating platforms for transportation",
  "A space battle with laser beams and massive explosions",
  "A desert landscape with a massive pyramid and a hidden treasure",
  "A magical city with wizards casting spells and mythical creatures roaming the streets",
  "A dystopian wasteland with a massive airship hovering above",
  "A futuristic city with advanced robot police and criminals using high-tech gadgets",
  "A medieval jousting tournament with knights competing for glory and honor",
  "A fantasy castle with hidden passageways and a labyrinthine dungeon",
  "A futuristic airport with advanced spaceplanes and a bustling crowd",
  "A city with massive, towering buildings and a bustling public transportation system",
  "A mythical creature such as a phoenix or a griffin perched on a castle tower",
  "A futuristic city with massive flying drones patrolling the skies",
  "A space station with astronauts conducting scientific experiments",
  "A medieval village with a massive castle in the distance",
  "A fantasy landscape with a unicorn grazing in a meadow",
  "A dystopian city with advanced robotic factories"
];
